In [1]:
import numpy as np
import os

In [2]:
os.chdir('..')

### Periodic energies

In [3]:
def calc_periodic_energy(lattice, interactions):
    energy = 0
    
    nx = lattice.shape[0]
    ny = lattice.shape[1]
    
    for i in range(lattice.shape[0]):
        for j in range(lattice.shape[1]):
            inn =  i - 1 if (i - 1 >= 0) else lattice.shape[0] - 1
            jnn =  j - 1 if (j - 1 >= 0) else lattice.shape[1] - 1

            energy += lattice[i,j] * (lattice[inn,j] * interactions[nx + inn,j] + lattice[i,jnn] * interactions[i, jnn])
            
    return energy
            

In [5]:
path = "init/periodic/prob_0.000000/X_10_Y_10/seed_"
seed = 42

for i in range(42,52):
    run_path = path + f"{i}/error_class_I"
    interactions = np.loadtxt(f"{run_path}/interactions/interactions.txt")
    
    lattice_names = os.listdir(f'{run_path}/lattice/')

    for ln in lattice_names:
        energy = ln.split('_')[1].split('.')[0]
        lattice = np.loadtxt(f"{run_path}/lattice/{ln}")
        calc_energy = calc_periodic_energy(lattice, interactions)
        
        if (int(energy) - calc_energy) != 0:
            print(calc_energy - int(energy))

### Open boundary

In [17]:
def calc_open_energy(lattice_data, interactions_data, nx, ny):
    
    energy=0
    
    for i in range(nx): 
        for j in range(ny):
            s_ij = lattice_data[i][j]
            s_up = lattice_data[i - 1][j] if (i > 0) else 0
            s_left = lattice_data[i][j - 1] if (j > 0) else 0
            inn =  nx + i - 1 if (i > 0) else 0
            jnn =  (j - 1) if (j > 0) else 0
                
            energy += s_ij * (s_up * interactions_data[inn][j] + s_left * interactions_data[i][jnn])
    return energy

In [19]:
for i in range(10):
    interactions = np.loadtxt(f"interactions/interactions_{i}/interactions.txt")
    
    lattice_names = os.listdir(f'lattice/lattice_{i}')
    
    for ln in lattice_names:
        energy = ln.split('_')[1].split('.')[0]
        lattice = np.loadtxt(f"lattice/lattice_{i}/{ln}")
        
        calc_energy = calc_open_energy(lattice, interactions, lattice.shape[0], lattice.shape[1])
        
        if (int(energy) - calc_energy) != 0:
            print(calc_energy - int(energy))

In [2]:
interactions_data = np.loadtxt('../init/open/prob_0.400000/X_12_Y_12/seed_44/error_class_I/interactions/interactions.txt')
lattice_data = np.loadtxt('../error_lattice.txt')

nx = 12
ny = 12

flat_lattice_data = lattice_data.flatten()
flat_interaction_data = interactions_data.flatten()

FileNotFoundError: ../error_lattice.txt not found.

In [3]:
flat_interaction_data

NameError: name 'flat_interaction_data' is not defined

This is calc for open boundary energy taken from wang landau utils

In [1]:
import numpy as np
import os

In [6]:
def calc_energy(lattice_data, interactions_data, nx, ny):
    
    energy=0
    
    for i in range(nx): 
        for j in range(ny):
            s_ij = lattice_data[i][j]
            s_up = lattice_data[i - 1][j] if (i > 0) else 0
            s_left = lattice_data[i][j - 1] if (j > 0) else 0
            inn =  nx + i - 1 if (i > 0) else 0
            jnn =  (j - 1) if (j > 0) else 0
                
            energy += s_ij * (s_up * interactions_data[inn][j] + s_left * interactions_data[i][jnn])
    return energy


In [22]:
names = os.listdir('../error')
interactions_data = np.loadtxt('../error/interactions_.txt')

before_energies = {}
before_name_energies = {}

after_energies = {}
after_name_energies = {}

for n in os.listdir("../error"):
    if "before" in n:
        walker = n.split('_')[2]
        energy = n.split('_')[3]
        lattice = np.loadtxt(f"../error/{n}")
        
        before_name_energies[walker] = int(energy.split('.')[0])
        before_energies[walker] = calc_energy(lattice, interactions_data, 12, 12)
        
    elif "after" in n:
        walker = n.split('_')[2]
        energy = n.split('_')[3]
        lattice = np.loadtxt(f"../error/{n}")
        
        after_name_energies[walker] = int(energy.split('.')[0])
        after_energies[walker] = calc_energy(lattice, interactions_data, 12, 12)

In [23]:
for i in range(50):
    energy_diff_before = before_energies[str(i)] - before_name_energies[str(i)]
    energy_diff_after = after_energies[str(i)] - after_name_energies[(str(i))]
    
    if (energy_diff_before!=0):
        print(f"Walker {i} with energy diff before {energy_diff_before}")
    if (energy_diff_after!=0):
        print(f"Walker {i} with energy diff after {energy_diff_after}")

Walker 5 with energy diff before -12.0
Walker 5 with energy diff after -12.0
Walker 6 with energy diff before -4.0
Walker 6 with energy diff after -4.0
Walker 7 with energy diff before 12.0
Walker 7 with energy diff after 12.0
Walker 8 with energy diff before 14.0
Walker 8 with energy diff after 14.0
Walker 9 with energy diff before 2.0
Walker 9 with energy diff after 2.0
Walker 10 with energy diff before 2.0
Walker 10 with energy diff after 2.0
Walker 11 with energy diff before 18.0
Walker 11 with energy diff after 20.0
Walker 12 with energy diff before 8.0
Walker 12 with energy diff after 8.0
Walker 13 with energy diff before 6.0
Walker 13 with energy diff after 6.0
Walker 14 with energy diff before -2.0
Walker 14 with energy diff after -2.0
Walker 15 with energy diff before 4.0
Walker 15 with energy diff after 4.0
Walker 16 with energy diff before -2.0
Walker 17 with energy diff before 10.0
Walker 17 with energy diff after 10.0
Walker 18 with energy diff after 2.0
Walker 19 with ene

In [52]:
lattice5b = np.loadtxt('../error/lattice_before_5_-162.txt')
lattice5a = np.loadtxt('../error/lattice_after_5_-158.txt')

print(calc_energy(lattice5b, interactions_data, 12, 12))
print(calc_energy(lattice5a, interactions_data, 12, 12))

print(lattice5b - lattice5a )

up  -1.0 left 1.0 spin -1.0
up interaction -1.0 left interaction -1.0
-150.0
up  -1.0 left -1.0 spin -1.0
up interaction -1.0 left interaction -1.0
-148.0
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
nx = 12
ny = 12

lattice = np.ones((12,12))
interactions = np.ones((24,12))

i = 3
j = 3

ipp = (i + 1) if (i + 1 < nx) else 0
inn = (i - 1) if (i - 1 >= 0) else nx - 1
jpp = (j + 1) if (j + 1 < ny) else 0
jnn = (j - 1) if (j - 1 >= 0) else ny - 1

old_energy = -1*lattice[i,j]*(lattice[inn, j]*interactions[nx + inn, j] + lattice[i,jnn]*interactions[i,jnn] + lattice[ipp,j]*interactions[nx + i,j] + lattice[i,jpp]*interactions[i,j])
new_energy = -1*old_energy

In [59]:
print(old_energy)
print(new_energy)

-4.0
4.0


This is calc taken from indices open periodic

In [7]:
lattice = np.arange(nx*ny).reshape(nx,ny)

Y2 = int(ny/2)

lattice_b = np.zeros((nx,Y2))
lattice_w = np.zeros((nx,Y2))

In [8]:
# Get black and white lattices
for i in range(nx):
    if i%2 == 0:
        lattice_b[i,:] = lattice[i,0::2]
        lattice_w[i,:] = lattice[i,1::2]
    else:
        lattice_b[i,:] = lattice[i,1::2]
        lattice_w[i,:] = lattice[i,0::2]

In [14]:
interactions = np.arange(2*nx*ny)

PERIODIC

In [8]:
# is_black = True

# energy = 0

# for tid in range(nx*Y2):
    
#         i = int(tid//Y2)
#         j = tid % Y2

#         ipp = (i + 1) if (i + 1 < nx) else 0
#         inn = (i - 1) if (i - 1 >= 0) else nx - 1
#         jpp = (j + 1) if (j + 1 < Y2) else 0
#         jnn = (j - 1) if (j - 1 >= 0) else Y2 - 1

#         if (is_black):
            
#             icpp = 2*(nx-1)*Y2 + 2*(Y2*(i+1) + j) + i%2
            
#             icnn = 2*(nx-1)*Y2 + 2*(Y2*(inn+1) + j) + i%2

#             joff = jpp if (i%2) else jnn
            
#             if (i % 2):
#                 if (j+1 >= Y2):
#                     jcoff = 2*(i*Y2 + j + 1) - 1
                
#                 else:
#                     jcoff = 2*(i*Y2 + joff) - 1
#             else:
#                 jcoff = 2 * (i*Y2 + joff) + 1

#             energy += flat_lattice_data[int(lattice_b[i,j])] * ( \
#                 flat_lattice_data[int(lattice_w[inn,j])]*flat_interaction_data[int(interactions[icnn])] \
#                 + flat_lattice_data[int(lattice_w[ipp,j])]*flat_interaction_data[int(interactions[icpp])] \
#                 + flat_lattice_data[int(lattice_w[i,j])]*flat_interaction_data[int(interactions[2*(i*Y2+j)])] \
#                 + flat_lattice_data[int(lattice_w[i, joff])]*flat_interaction_data[int(interactions[jcoff])] \
#             )

#             print("Spin of interest:", lattice_b[i,j], ": ", flat_lattice_data[int(lattice_b[i,j])])
#             print("Up neighbor:", lattice_w[inn,j], ": ", flat_lattice_data[int(lattice_w[inn,j])], "with", interactions[icnn], ": ", flat_interaction_data[int(interactions[icnn])])
#             print("Down neighbor:", lattice_w[ipp,j], ": ", flat_lattice_data[int(lattice_w[ipp,j])],  "with", interactions[icpp], ": ", flat_interaction_data[int(interactions[2*(i*Y2+j)])])
#             print("Right neighbor:", lattice_w[i,j], ": ", flat_lattice_data[int(lattice_w[i,j])], "with", interactions[2*(i*Y2+j)], ": ", flat_interaction_data[int(interactions[2*(i*Y2+j)])])
#             print("Left neighbor:", lattice_w[i, joff], ": ", flat_lattice_data[int(lattice_w[i, joff])], "with", interactions[jcoff], ": ", flat_interaction_data[int(interactions[jcoff])])
#             print("----------------------------------")



# print(energy, "\n")

            


OPEN

In [15]:
is_black = True

energy = 0

for tid in range(nx*Y2):
    
        i = int(tid/Y2)
        j = tid % Y2

        ipp = (i + 1) if (i + 1 < nx) else 0
        inn = (i - 1) if (i - 1 >= 0) else nx - 1
        jpp = (j + 1) if (j + 1 < Y2) else 0
        jnn = (j - 1) if (j - 1 >= 0) else Y2 - 1
        
        c_up = 1-int(inn/(nx-1))
        c_down = 1-int((i+1)/nx)
        
        if (is_black):
            
            icpp = 2*(nx-1)*Y2 + 2*(Y2*(i+1) + j) + i%2
            
            icnn = 2*(nx-1)*Y2 + 2*(Y2*(inn+1) + j) + i%2

            joff = jpp if (i%2) else jnn
            
            if (i % 2):
                c_side = 1-int((j+1)/Y2)
                
                if (j+1 >= Y2):
                    jcoff = 2*(i*Y2 + j + 1) - 1
                
                else:
                    jcoff = 2*(i*Y2 + joff) - 1
            else:
                c_side = 1-int(jnn/(Y2-1))
                
                jcoff = 2 * (i*Y2 + joff) + 1

            energy += flat_lattice_data[int(lattice_b[i,j])] * ( \
                c_up * flat_lattice_data[int(lattice_w[inn,j])] * flat_interaction_data[int(interactions[icnn])] \
                + c_down * flat_lattice_data[int(lattice_w[ipp,j])] * flat_interaction_data[int(interactions[icpp])] \
                + flat_lattice_data[int(lattice_w[i,j])]*flat_interaction_data[int(interactions[2*(i*Y2+j)])] \
                + c_side * flat_lattice_data[int(lattice_w[i, joff])]*flat_interaction_data[int(interactions[jcoff])] \
            )

                
            # print("Spin of interest:", lattice_b[i,j])
            # print("Up neighbor:", lattice_w[inn,j], "with", c_up, "and interaction", interactions[icnn])
            # print("Down neighbor:", lattice_w[ipp,j], "with", c_down, "and interaction", interactions[icpp])
            # print("Right neighbor:", lattice_w[i,j], "with", 1, "and interaction", interactions[2*(i*Y2+j)])
            # print("Left neighbor:", lattice_w[i, joff], "with", c_side, "and interaction", interactions[jcoff])
            # print("----------------------------------")


In [17]:
print(energy)

176.0
