In [7]:
import numpy as np
import os

In [12]:
def generate_intervals(E_min, E_max, N):
    R = E_max - E_min
    L = R / (1 + 0.25 * (N - 1))
    step_size = 0.25 * L
    
    intervals = []
    start = E_min
    
    for _ in range(N):
        end = start + L
        intervals.append((start, end))
        start += step_size
    
    return intervals

# Example usage:
E_min = -288
E_max = 288
N = 10  # number of intervals

intervals = generate_intervals(E_min, E_max, N)
for interval in intervals:
    print(interval)

(-288, -110.76923076923077)
(-243.69230769230768, -66.46153846153845)
(-199.38461538461536, -22.153846153846132)
(-155.07692307692304, 22.15384615384619)
(-110.76923076923073, 66.4615384615385)
(-66.46153846153842, 110.7692307692308)
(-22.153846153846118, 155.0769230769231)
(22.15384615384619, 199.38461538461542)
(66.4615384615385, 243.69230769230774)
(110.7692307692308, 288.0)


In [10]:
3.75/5

0.75

In [17]:
l_names = [f"lattice_{i}.txt" for i in range(16)]
i_names = [f"interactions_{i}.txt" for i in range(1)]

In [18]:
is_black = True

for l in range(16):
    lattice = np.loadtxt(f'../{l_names[l]}')
    interactions = np.loadtxt(f'../{i_names[0]}')
    interactions = interactions.reshape(-1)
    
    X = lattice.shape[0]
    Y = lattice.shape[1]
    Y2 = int(Y/2)
    
    lattice_b = np.zeros((X,Y2))
    lattice_w = np.zeros((X,Y2))

    lattice_b[0::2,:] = lattice[0::2,0::2]
    lattice_b[1::2,:] = lattice[1::2,1::2]
    
    lattice_w[0::2,:] = lattice[0::2,1::2]
    lattice_w[1::2,:] = lattice[1::2,0::2]

    energy = 0 
    
    for tid in range(X*Y2):
    
        i = int(tid/Y2)
        j = tid % Y2

        ipp = (i + 1) if (i + 1 < X) else 0
        inn = (i - 1) if (i - 1 >= 0) else X - 1
        jpp = (j + 1) if (j + 1 < Y2) else 0
        jnn = (j - 1) if (j - 1 >= 0) else Y2 - 1

        if (is_black):
            
            icpp = 2*(X-1)*Y2 + 2*(Y2*(i+1) + j) + i%2
            
            icnn = 2*(X-1)*Y2 + 2*(Y2*(inn+1) + j) + i%2

            joff = jpp if (i%2) else jnn
            
            if (i % 2):
                if (j+1 >= Y2):
                    jcoff = 2*(i*Y2 + j + 1) - 1
                
                else:
                    jcoff = 2*(i*Y2 + joff) - 1
            else:
                jcoff = 2 * (i*Y2 + joff) + 1

            energy += lattice_b[i,j]*(lattice_w[inn,j]*interactions[icnn] + lattice_w[ipp,j]*interactions[icpp] + 
                                      lattice_w[i,j]*interactions[2*(i*Y2+j)] + lattice_w[i, joff]*interactions[jcoff])
    print(energy)

0.0
-8.0
-12.0
-12.0
-4.0
28.0
-16.0
-24.0
-40.0
-4.0
4.0
28.0
-20.0
-16.0
-20.0
4.0


In [10]:
lattice_w

array([[-1.,  1., -1., -1.,  1., -1.],
       [-1., -1., -1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1.],
       [ 1., -1., -1., -1., -1.,  1.],
       [-1.,  1., -1., -1., -1., -1.],
       [ 1., -1.,  1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [-1.,  1.,  1., -1.,  1.,  1.],
       [-1., -1.,  1., -1.,  1., -1.],
       [-1., -1.,  1.,  1., -1., -1.],
       [ 1., -1.,  1.,  1., -1.,  1.],
       [ 1., -1.,  1.,  1., -1.,  1.]])

In [5]:
lattice

array([[ 1., -1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1., -1., -1.],
       [-1.,  1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.],
       [ 1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1., -1.],
       [ 1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1., -1.],
       [-1., -1.,  1.,  1.,  1., -1.,  1., -1., -1., -1., -1., -1.],
       [ 1.,  1., -1.,  1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1., -1., -1., -1., -1., -1.,  1., -1.,  1., -1.],
       [-1., -1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.],
       [-1., -1., -1., -1., -1.,  1.,  1., -1., -1.,  1., -1., -1.],
       [-1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.],
       [ 1.,  1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,  1.,  1.],
       [ 1., -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1.]])

In [6]:
np.unique(interactions,return_counts=True)

(array([-1.,  1.]), array([141, 147]))

In [7]:
interactions.reshape(2*X,Y)

array([[-1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.],
       [-1., -1., -1., -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1.],
       [-1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1., -1.],
       [ 1.,  1., -1.,  1., -1., -1.,  1., -1., -1., -1., -1.,  1.],
       [ 1., -1., -1.,  1., -1., -1.,  1., -1.,  1.,  1., -1., -1.],
       [ 1., -1.,  1., -1.,  1., -1., -1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1., -1., -1.],
       [ 1.,  1., -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1., -1.],
       [ 1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1.],
       [ 1., -1., -1.,  1.,  1.,  1., -1., -1., -1., -1., -1.,  1.],
       [ 1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1.],
       [-1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.],
       [ 1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1., -1.],
       [-1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., -1., -1., -1., -

In [8]:
interactions.reshape(2*X,Y)[12:,:]

array([[ 1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1., -1.],
       [-1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., -1., -1., -1., -1.,  1.,  1., -1.,  1., -1., -1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.],
       [-1., -1., -1.,  1., -1.,  1., -1.,  1.,  1., -1., -1., -1.],
       [ 1., -1.,  1., -1., -1., -1., -1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1.,  1., -1., -1.,  1., -1.,  1.],
       [-1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.,  1., -1., -1.],
       [-1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1., -1.]])