In [1]:
import numpy as np
import os

os.chdir('..')

In [5]:
#interactions = np.ones(2*X*Y)
interactions = np.loadtxt("interactions/prob_0.000000/X_10_Y_10/interactions_seed_42.txt")
interactions = interactions.reshape(-1)

In [6]:
def calc_energy(lattice, interactions):
    energy = 0
    
    for i in range(lattice.shape[0]):
        for j in range(lattice.shape[1]):
            inn = i - 1 if (i-1) >= 0 else lattice.shape[0] - 1 
            jnn = j - 1 if (j-1) >= 0 else lattice.shape[1] - 1

            energy += (lattice[i,j]*lattice[inn,j]*interactions[lattice.shape[0]*lattice.shape[1] + inn*lattice.shape[1] + j] + lattice[i,j]*lattice[i,jnn]*interactions[i*lattice.shape[1] + jnn])
            #energy += (lattice[i,j]*lattice[inn,j] + lattice[i,j]*lattice[i,jnn])

    return energy

In [8]:
for i in os.listdir('lattice/'):
    lattice = np.loadtxt(f'lattice/{i}')
    print(i)
    print(calc_energy(lattice, interactions))

lattice_-100.txt
-100.0
lattice_-48.txt
-48.0
lattice_-156.txt
-156.0
lattice_20.txt
20.0
lattice_-4.txt
-4.0
lattice_-72.txt
-72.0
lattice_72.txt
72.0
lattice_-128.txt
-128.0
lattice_56.txt
56.0
lattice_108.txt
108.0
lattice_-20.txt
-20.0
lattice_164.txt
164.0
lattice_116.txt
116.0
lattice_140.txt
140.0
lattice_-176.txt
-176.0


In [13]:
import itertools

values = [-1, 1]

energies = []

# Generate all combinations using itertools.product
combinations = list(itertools.product(values, repeat=X*Y))

# Print the combinations
for combination in combinations:
    energies.append(calc_energy(np.array(combination).reshape(X,Y), interactions))

set(energies)

{-28.0,
 -24.0,
 -20.0,
 -16.0,
 -12.0,
 -8.0,
 -4.0,
 0.0,
 4.0,
 8.0,
 12.0,
 16.0,
 20.0,
 24.0,
 28.0}

In [49]:
nx = 12
ny = 12

interactions = np.arange(nx*ny*2)
lattice = np.arange(nx*ny)

inter = interactions.reshape((2*nx,ny))
lat = lattice.reshape((nx,ny))

In [50]:
for tid in range(nx*ny):
    i = int(tid/ny)
    j =  tid%ny

    ipp = (i + 1) if (i + 1 < nx) else 0
    inn = (i - 1) if (i - 1 >= 0) else nx - 1
    jpp = (j + 1) if (j + 1 < ny) else 0
    jnn = (j - 1) if (j - 1 >= 0) else ny - 1

    print(f"spin of interest {lattice[i*ny+j]}") 
    print(f"Down neighbor {lattice[inn*ny+j]} with interaction {interactions[nx*ny + inn*ny+j]}")
    print("-------------------------")

spin of interest 0
Down neighbor 132 with interaction 276
-------------------------
spin of interest 1
Down neighbor 133 with interaction 277
-------------------------
spin of interest 2
Down neighbor 134 with interaction 278
-------------------------
spin of interest 3
Down neighbor 135 with interaction 279
-------------------------
spin of interest 4
Down neighbor 136 with interaction 280
-------------------------
spin of interest 5
Down neighbor 137 with interaction 281
-------------------------
spin of interest 6
Down neighbor 138 with interaction 282
-------------------------
spin of interest 7
Down neighbor 139 with interaction 283
-------------------------
spin of interest 8
Down neighbor 140 with interaction 284
-------------------------
spin of interest 9
Down neighbor 141 with interaction 285
-------------------------
spin of interest 10
Down neighbor 142 with interaction 286
-------------------------
spin of interest 11
Down neighbor 143 with interaction 287
----------------

In [30]:
num_iterations = 10

In [29]:
threads = 16

In [31]:
it = 0
for i in range(10):
    print(it)
    it += num_iterations
    print(it)
    it += threads
    print(it)
    it += threads

0
10
26
42
52
68
84
94
110
126
136
152
168
178
194
210
220
236
252
262
278
294
304
320
336
346
362
378
388
404


In [23]:
inter

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167],
       [168, 169, 170, 171, 172, 1

In [12]:
def generate_intervals(E_min, E_max, N):
    R = E_max - E_min
    L = R / (1 + 0.25 * (N - 1))
    step_size = 0.25 * L
    
    intervals = []
    start = E_min
    
    for _ in range(N):
        end = start + L
        intervals.append((start, end))
        start += step_size
    
    return intervals

# Example usage:
E_min = -288
E_max = 288
N = 10  # number of intervals

intervals = generate_intervals(E_min, E_max, N)
for interval in intervals:
    print(interval)

(-288, -110.76923076923077)
(-243.69230769230768, -66.46153846153845)
(-199.38461538461536, -22.153846153846132)
(-155.07692307692304, 22.15384615384619)
(-110.76923076923073, 66.4615384615385)
(-66.46153846153842, 110.7692307692308)
(-22.153846153846118, 155.0769230769231)
(22.15384615384619, 199.38461538461542)
(66.4615384615385, 243.69230769230774)
(110.7692307692308, 288.0)


In [10]:
3.75/5

0.75

In [32]:
l_names = [f"lattice_{i}.txt" for i in range(16)]
i_names = [f"interactions_{i}.txt" for i in range(1)]

In [33]:
is_black = True

for l in range(16):
    lattice = np.loadtxt(f'../{l_names[l]}')
    interactions = np.loadtxt(f'../{i_names[0]}')
    interactions = interactions.reshape(-1)
    
    X = lattice.shape[0]
    Y = lattice.shape[1]
    Y2 = int(Y/2)
    
    lattice_b = np.zeros((X,Y2))
    lattice_w = np.zeros((X,Y2))

    lattice_b[0::2,:] = lattice[0::2,0::2]
    lattice_b[1::2,:] = lattice[1::2,1::2]
    
    lattice_w[0::2,:] = lattice[0::2,1::2]
    lattice_w[1::2,:] = lattice[1::2,0::2]

    energy = 0 
    
    for tid in range(X*Y2):
    
        i = int(tid/Y2)
        j = tid % Y2

        ipp = (i + 1) if (i + 1 < X) else 0
        inn = (i - 1) if (i - 1 >= 0) else X - 1
        jpp = (j + 1) if (j + 1 < Y2) else 0
        jnn = (j - 1) if (j - 1 >= 0) else Y2 - 1

        if (is_black):
            
            icpp = 2*(X-1)*Y2 + 2*(Y2*(i+1) + j) + i%2
            
            icnn = 2*(X-1)*Y2 + 2*(Y2*(inn+1) + j) + i%2

            joff = jpp if (i%2) else jnn
            
            if (i % 2):
                if (j+1 >= Y2):
                    jcoff = 2*(i*Y2 + j + 1) - 1
                
                else:
                    jcoff = 2*(i*Y2 + joff) - 1
            else:
                jcoff = 2 * (i*Y2 + joff) + 1

            energy += lattice_b[i,j]*(lattice_w[inn,j]*interactions[icnn] + lattice_w[ipp,j]*interactions[icpp] + 
                                      lattice_w[i,j]*interactions[2*(i*Y2+j)] + lattice_w[i, joff]*interactions[jcoff])
    print(energy)

16.0
4.0
8.0
-8.0
8.0
4.0
4.0
0.0
0.0
0.0
8.0
4.0
0.0
-4.0
-4.0
0.0


In [10]:
lattice_w

array([[-1.,  1., -1., -1.,  1., -1.],
       [-1., -1., -1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1.],
       [ 1., -1., -1., -1., -1.,  1.],
       [-1.,  1., -1., -1., -1., -1.],
       [ 1., -1.,  1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [-1.,  1.,  1., -1.,  1.,  1.],
       [-1., -1.,  1., -1.,  1., -1.],
       [-1., -1.,  1.,  1., -1., -1.],
       [ 1., -1.,  1.,  1., -1.,  1.],
       [ 1., -1.,  1.,  1., -1.,  1.]])

In [5]:
lattice

array([[ 1., -1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1., -1., -1.],
       [-1.,  1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.],
       [ 1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1., -1.],
       [ 1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1., -1.],
       [-1., -1.,  1.,  1.,  1., -1.,  1., -1., -1., -1., -1., -1.],
       [ 1.,  1., -1.,  1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1., -1., -1., -1., -1., -1.,  1., -1.,  1., -1.],
       [-1., -1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.],
       [-1., -1., -1., -1., -1.,  1.,  1., -1., -1.,  1., -1., -1.],
       [-1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.],
       [ 1.,  1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,  1.,  1.],
       [ 1., -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1.]])

In [6]:
np.unique(interactions,return_counts=True)

(array([-1.,  1.]), array([141, 147]))

In [7]:
interactions.reshape(2*X,Y)

array([[-1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.],
       [-1., -1., -1., -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1.],
       [-1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1., -1.],
       [ 1.,  1., -1.,  1., -1., -1.,  1., -1., -1., -1., -1.,  1.],
       [ 1., -1., -1.,  1., -1., -1.,  1., -1.,  1.,  1., -1., -1.],
       [ 1., -1.,  1., -1.,  1., -1., -1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1., -1., -1.],
       [ 1.,  1., -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1., -1.],
       [ 1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1.],
       [ 1., -1., -1.,  1.,  1.,  1., -1., -1., -1., -1., -1.,  1.],
       [ 1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1.],
       [-1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.],
       [ 1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1., -1.],
       [-1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., -1., -1., -1., -

In [8]:
interactions.reshape(2*X,Y)[12:,:]

array([[ 1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1., -1.],
       [-1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., -1., -1., -1., -1.,  1.,  1., -1.,  1., -1., -1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.],
       [-1., -1., -1.,  1., -1.,  1., -1.,  1.,  1., -1., -1., -1.],
       [ 1., -1.,  1., -1., -1., -1., -1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1.,  1., -1., -1.,  1., -1.,  1.],
       [-1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.,  1., -1., -1.],
       [-1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1., -1.]])