In [1]:
import numpy as np
import os

In [2]:
os.chdir('..')

In [10]:
for i in range(8):
    lattice = np.loadtxt(f'lattice_{i}.txt')
    
    wave_vector = 2*np.pi/lattice.shape[0]
    
    c_sum = 0
    
    for k in range(lattice.shape[0]):
        for j in range(lattice.shape[1]):
            c_sum += np.exp(k*1j*wave_vector)*lattice[k,j]
    print(np.abs(c_sum)**2)

682.6973485926736
4.000000000000057
14.928203230275438
376.4204710660615
4700.660895063402
447.8460969082651
3189.2765074303393
2443.9381426862833


In [9]:
# Lattice sizes
X = 8
Y = 8
Y2 = int(Y/2)

In [10]:
# Create lattice
lattice = np.arange(X*Y).reshape(X,Y)

lattice_b = np.zeros((X,Y2))
lattice_w = np.zeros((X,Y2))

In [11]:
# Get black and white lattices
for i in range(X):
    if i%2 == 0:
        lattice_b[i,:] = lattice[i,0::2]
        lattice_w[i,:] = lattice[i,1::2]
    else:
        lattice_b[i,:] = lattice[i,1::2]
        lattice_w[i,:] = lattice[i,0::2]

In [12]:
# Get interactions
interactions = np.arange(2*X*Y)
interactions_reshaped = interactions.reshape((2*X,Y))

### 1. Periodic Boundary Conditions

In [22]:
# Check whether 
is_black = False

In [24]:
for tid in range(X*Y2):
    
        i = int(tid/Y2)
        j = tid % Y2

        ipp = (i + 1) if (i + 1 < X) else 0
        inn = (i - 1) if (i - 1 >= 0) else X - 1
        jpp = (j + 1) if (j + 1 < Y2) else 0
        jnn = (j - 1) if (j - 1 >= 0) else Y2 - 1

        if (is_black):
            
            icpp = 2*(X-1)*Y2 + 2*(Y2*(i+1) + j) + i%2
            
            icnn = 2*(X-1)*Y2 + 2*(Y2*(inn+1) + j) + i%2

            joff = jpp if (i%2) else jnn
            
            if (i % 2):
                if (j+1 >= Y2):
                    jcoff = 2*(i*Y2 + j + 1) - 1
                
                else:
                    jcoff = 2*(i*Y2 + joff) - 1
            else:
                jcoff = 2 * (i*Y2 + joff) + 1

            if tid == 14:
                print("Spin of interest:", lattice_b[i,j])
                print("Up neighbor:", lattice_w[inn,j], "with", interactions[icnn])
                print("Down neighbor:", lattice_w[ipp,j], "with", interactions[icpp])
                print("Right neighbor:", lattice_w[i,j], "with", interactions[2*(i*Y2+j)])
                print("Left neighbor:", lattice_w[i, joff], "with", interactions[jcoff])
                print("----------------------------------")
    
        else:
        
            icpp = 2*(X - 1)*Y2 + 2*(Y2*(i+1) + j) + (i+1)%2
            icnn = 2*(X - 1)*Y2 + 2*(Y2*(inn+1) + j) + (i+1)%2

            joff = jnn if (i%2) else jpp

            if (i%2):
                jcoff = 2*(i*Y2 + joff) + 1
            else:
                if (j+1 >= Y2):
                    jcoff = 2*(i*Y2 + j + 1) - 1
                else:
                    jcoff = 2*(i*Y2 + joff) - 1
            
            if tid == 12:
                print("Spin of interest:", lattice_w[i,j])
                print("Up neighbor:", lattice_b[inn,j], "with", interactions[icnn])
                print("Down neighbor:", lattice_b[ipp,j], "with", interactions[icpp])
                print("Right neighbor:", lattice_b[i,j], "with", interactions[2*(i*Y2+j)])
                print("Left neighbor:", lattice_b[i, joff], "with", interactions[jcoff])
                print("----------------------------------")

Spin of interest: 24.0
Up neighbor: 16.0 with 80
Down neighbor: 32.0 with 88
Right neighbor: 25.0 with 24
Left neighbor: 31.0 with 31
----------------------------------


In [34]:
lattice

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [35]:
interactions_reshaped[:X,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [36]:
interactions_reshaped[-X:,:]

array([[48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95]])

### 2. Open Boundary Conditions

In [8]:
# Check whether 
is_black = True

In [9]:
for tid in range(X*Y2):
    
        i = int(tid/Y2)
        j = tid % Y2

        ipp = (i + 1) if (i + 1 < X) else 0
        inn = (i - 1) if (i - 1 >= 0) else X - 1
        jpp = (j + 1) if (j + 1 < Y2) else 0
        jnn = (j - 1) if (j - 1 >= 0) else Y2 - 1
        
        c_up = 1-int(inn/(X-1))
        c_down = 1-int((i+1)/X)
        
        if (is_black):
            
            icpp = 2*(X-1)*Y2 + 2*(Y2*(i+1) + j) + i%2
            
            icnn = 2*(X-1)*Y2 + 2*(Y2*(inn+1) + j) + i%2

            joff = jpp if (i%2) else jnn
            
            if (i % 2):
                c_side = 1-int((j+1)/Y2)
                
                if (j+1 >= Y2):
                    jcoff = 2*(i*Y2 + j + 1) - 1
                
                else:
                    jcoff = 2*(i*Y2 + joff) - 1
            else:
                c_side = 1-int(jnn/(Y2-1))
                
                jcoff = 2 * (i*Y2 + joff) + 1

                
            print("Spin of interest:", lattice_b[i,j])
            print("Up neighbor:", lattice_w[inn,j], "with", c_up)
            print("Down neighbor:", lattice_w[ipp,j], "with", c_down)
            print("Right neighbor:", lattice_w[i,j], "with", 1)
            print("Left neighbor:", lattice_w[i, joff], "with", c_side)
            print("----------------------------------")
    
        else:
        
            icpp = 2*(X - 1)*Y2 + 2*(Y2*(i+1) + j) + (i+1)%2
            icnn = 2*(X - 1)*Y2 + 2*(Y2*(inn+1) + j) + (i+1)%2

            joff = jnn if (i%2) else jpp

            if (i%2):
                c_side = 1-int(jnn/(Y2-1))
                
                jcoff = 2*(i*Y2 + joff) + 1
            else:
                
                c_side = 1-int((j+1)/Y2)
                
                
                if (j+1 >= Y2):
                    jcoff = 2*(i*Y2 + j + 1) - 1
                else:
                    jcoff = 2*(i*Y2 + joff) - 1

            print("Spin of interest:", lattice_w[i,j])
            print("Up neighbor:", lattice_b[inn,j], "with", c_up)
            print("Down neighbor:", lattice_b[ipp,j], "with", c_down)
            print("Left neighbor:", lattice_b[i,j], "with", 1)
            print("Right neighbor:", lattice_b[i, joff], "with", c_side)
            print("----------------------------------")

Spin of interest: 0.0
Up neighbor: 30.0 with 0
Down neighbor: 6.0 with 1
Right neighbor: 1.0 with 1
Left neighbor: 5.0 with 0
----------------------------------
Spin of interest: 2.0
Up neighbor: 32.0 with 0
Down neighbor: 8.0 with 1
Right neighbor: 3.0 with 1
Left neighbor: 1.0 with 1
----------------------------------
Spin of interest: 4.0
Up neighbor: 34.0 with 0
Down neighbor: 10.0 with 1
Right neighbor: 5.0 with 1
Left neighbor: 3.0 with 1
----------------------------------
Spin of interest: 7.0
Up neighbor: 1.0 with 1
Down neighbor: 13.0 with 1
Right neighbor: 6.0 with 1
Left neighbor: 8.0 with 1
----------------------------------
Spin of interest: 9.0
Up neighbor: 3.0 with 1
Down neighbor: 15.0 with 1
Right neighbor: 8.0 with 1
Left neighbor: 10.0 with 1
----------------------------------
Spin of interest: 11.0
Up neighbor: 5.0 with 1
Down neighbor: 17.0 with 1
Right neighbor: 10.0 with 1
Left neighbor: 6.0 with 0
----------------------------------
Spin of interest: 12.0
Up neig

In [12]:
lattice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])